
{
	"Communication": "COM", 
	"Chemistry": "CHEM", 
	"Biology": "BIOL", 
	"Foreign Language": "CHIN", 
	"Design": "DESIGN", 
	"Informatics": "INFO", 
	"English": "ENGL", 
	"Computer Science": "CSE", 
	"Economics": "ECON", 
	"History": "HIST", 
	"International Studies": "JSIS", 
	"Math": "MATH", 
	"Music": "MUSIC", 
	"Philosophy": "PHIL", 
	"Physics": "PHYS", 
	"Psychology": "PSYCH", 
	"Sociology": "SOC", 
	"Statistics": "STAT", 
	"Architecture": "ARCH", 
	"Accounting": "ACCTG", 
	"Finance": "FIN", 
	"Marketing": "MKTG", 
	"Education": "EDUC", 
	"HCDE": "HCDE", 
	"Bioengineering": "BIOEN", 
	"ACMS": "AMATH", 
	"Applied Math": "AMATH", 
	"Drama": "DRAMA", 
	"Art": "ART", 
	"Operations Management": "OPMGT"
}